// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlclxbdtsu1kGaTgbZuhssay5Itgp3tyc',
    appId: '1:95327286501:web:fb86a3dd37952b63d0900c',
    messagingSenderId: '95327286501',
    projectId: 'todolistapp-14981',
    authDomain: 'todolistapp-14981.firebaseapp.com',
    storageBucket: 'todolistapp-14981.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWi700ACkyK6zcPFxrzVjY1vGF8loMbc',
    appId: '1:95327286501:android:7e3de010746e029ad0900c',
    messagingSenderId: '95327286501',
    projectId: 'todolistapp-14981',
    storageBucket: 'todolistapp-14981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA228pg-Et9H2ZaGMgEBClVIQPLvq_jU40',
    appId: '1:95327286501:ios:bffc51b4d00f3d92d0900c',
    messagingSenderId: '95327286501',
    projectId: 'todolistapp-14981',
    storageBucket: 'todolistapp-14981.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA228pg-Et9H2ZaGMgEBClVIQPLvq_jU40',
    appId: '1:95327286501:ios:bffc51b4d00f3d92d0900c',
    messagingSenderId: '95327286501',
    projectId: 'todolistapp-14981',
    storageBucket: 'todolistapp-14981.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlclxbdtsu1kGaTgbZuhssay5Itgp3tyc',
    appId: '1:95327286501:web:2d0bf759a1d23f04d0900c',
    messagingSenderId: '95327286501',
    projectId: 'todolistapp-14981',
    authDomain: 'todolistapp-14981.firebaseapp.com',
    storageBucket: 'todolistapp-14981.appspot.com',
  );
}
